title: "CHIKHI Sofiane"
email: sofiane0chihki@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hello world here's my personal Github web page it's for LHD Build 'Create a Personal Site with GitHub Pages' challenge
  and actually use it to promote myself :3 ofc
baseurl: "/"
url: "/portfolio-template"
twitter_username: mlhacks
github_username: Jensderpro

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
